# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

# .github/workflows/pkgdown.yml

name: Build and Deploy pkgdown

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
      with:
        r-version: '4.1.1'

    - name: Install Dependencies
      run: Rscript -e 'install.packages("pkgdown")'

    - name: Build pkgdown Site
      run: Rscript -e 'pkgdown::build_site()'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
